name: Site Technical Issue
description: Report technical issues such as broken links, missing media, outdated information, or issues with code examples.
labels: ["site-technical-issue"]
body:
  - type: checkboxes
    id: employee
    attributes:
      label: Temporal Affiliation
      options:
        - label: I am a Temporal employee
          required: false
  - type: textarea
    id: issue-location
    attributes:
      label: Content Issue
      description: What technical issue did you encounter and where did it happen? Please let us know the URL, an approximate location on that page, and any other details that will help us locate and correct the problem. We appreciate suggestions for how to fix the issue.
      placeholder: "URL, header, issue, suggested correction"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thanks for helping us improve our documentation."
